### ISSUE TITLE
Add ability to set default field names globally

### ISSUE THREAD

**Issue by vladshcherbin** [jagi/meteor-astronomy-timestamp-behavior#3]
Now, we can add the timestamp behaviour and specify, how the fields are named in the class. But is there a way to specify the names globally? For example, to use `created_at` and `updated_at` everywhere, where this behaviour is used.

**Comment by lukejagodzinski** [comment]
It probably is possible but I wouldn't recommend it :-). You would have to override default behavior options.

``` js
Astro.behaviors.timestamp.options.createdFieldName = 'created_at';
```

**Comment by vladshcherbin** [comment]
@jagi thanks for a possible workaround ;) so what would you recommend to do in such case?

**Comment by lukejagodzinski** [comment]
Hmm right now I think you can use this approach :). Just make sure that you change the options before any class definition.

**Comment by vladshcherbin** [comment]
Thanks, @jagi . I guess, I'll use class definition for now. Maybe later you will add a better way.
